spring.application.name=joblify
spring.profiles.active=dev

# Logging Configuration
logging.level.com.nijad.joblify=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.name=joblify.log

# Common properties
file.upload-path=uploads/
app.welcome-message=Welcome to Joblify Portal!
