# Prod profile
spring.datasource.url=jdbc:mysql://production-server:3306/joblify
spring.datasource.username=admin
spring.datasource.password=secure_password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

app.welcome-message=Welcome to Joblify Official Portal
